package bci.work;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;

import bci.work.category.Category;
import bci.work.creator.Creator;
import bci.notification.*;
import bci.notification.WorkObserver.ObserverType;

/**
 * Abstract class representing a Work item.
 */
public abstract class Work implements Serializable, Comparable<Work>, WorkSubject {
    @java.io.Serial
    private static final long serialVersionUID = 202507171003L;
    
    private int _id;
    private String _title;
    private int _price;
    private Category _category;
    private int _copiesTotal;
    private int _copiesAvailable;
    private List<WorkObserver> _observers = new ArrayList<>();

    public Work(int id, String title, int price, Category category, int copies) {
        _id = id;
        _title = title;
        _price = price;
        _category = category;
        _copiesTotal = copies;
        _copiesAvailable = copies;
    }    

    public int getId() { return _id; }
    public String getTitle() { return _title; }
    public int getPrice() { return _price; }
    public Category getCategory() { return _category; }
    public int getTotalCopies() { return _copiesTotal; }
    public int getAvailableCopies() { return _copiesAvailable; }
    public List<WorkObserver> getObservers() { return _observers; }
    public abstract String getType();

    public boolean isAvailable() { return _copiesAvailable > 0; }

    /**
     * Accept a WorkWriter to process this Work item.
     * 
     * @param writer the WorkWriter instance
     * @return the String representation generated by the writer
     */
    public abstract String accept(WorkWriter writer);

    @Override
    /**
     * @see java.lang.Object#toString()
     */
    public String toString() { return this.accept(new WorkWriter()); }

    /**
     * Update the number of total copies by n.
     * <p>
     * Available copies also update when increasing the total.
     * 
     * @param n the number of copies to add; can be positive (add) or negative (remove).
     */
    public void updateTotalCopies(int n) {
        _copiesTotal += n;
        updateAvailableCopies(n, false);
    }

    /**
     * Update the number of available copies by n.
     * <p>
     * Notifies all observers accordingly with the corresponding notification.
     * 
     * @param n the number of copies to add; can be positive (add) or negative (remove).
     * @param request true if the method is called from a request procedure, false otherwise
     */
    public void updateAvailableCopies(int n, boolean request) {
        if (request) // notify on every request
            notifyObservers(new RequestNotification(this));
        else if (_copiesAvailable == 0 && n > 0) { // notify when available
            notifyObservers(new AvailabilityNotification(this));
            _observers.removeIf(obs -> obs.getObserverType() == ObserverType.AVAILABILITY);
        }
        _copiesAvailable += n;
    }

    @Override
    /**
     * @see java.lang.Comparable#compareTo(Object)
     */
    public int compareTo(Work other) { return WorkComparator.byId().compare(this, other); }

    /**
     * Determine if the title matches the search criteria.
     * 
     * @param search the search string
     * @return true if the title contains the search string (case-insensitive), false otherwise
     */
    public boolean titleMatches(String search) { return getTitle().toLowerCase().contains(search); }

    /**
     * Determine if the work matches the search criteria.
     * 
     * @param search the search string
     * @return true if it matches, false otherwise
     */
    public abstract boolean matches(String search);

    @Override
    /**
     * @see bci.notification.WorkSubject#registerObserver(bci.notification.WorkObserver)
     */
    public void registerObserver(WorkObserver observer) { if (!_observers.contains(observer)) _observers.add(observer); }

    @Override
    /**
     * @see bci.notification.WorkSubject#removeObserver(bci.notification.WorkObserver)
     */
    public void removeObserver(WorkObserver observer) { _observers.remove(observer); }

    @Override
    /**
     * @see bci.notification.WorkSubject#notifyObservers()
     */
    public void notifyObservers(Notification n) {
        for (WorkObserver observer : _observers) { observer.addNotification(n); }
    }
}
